name: Pr agent - AI Code Review
on:
  pull_request:
    # THÊM danh sách types sau để đảm bảo tất cả các sự kiện chính được bắt
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
    types: [created]
jobs:
  pr-agent:
    name: PR Agent Review
    runs-on: ubuntu-latest # hoặc ubuntu-latest nếu ko dùng self-hosted runner
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PR Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.API_BASE: https://genai.vnpay.vn/aigateway/llm/v1
          OPENAI.KEY: ${{ secrets.OPENAI_KEY }}
          PR_REVIEWER.MODEL: "v_chat"
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: "true"
          # config.model: v_chat
          # github_action_config.auto_review: "true"
          # github_action_config.auto_describe: "true"
          # github_action_config.auto_improve: "true"
